### ISSUE TITLE
UnexpectedValueException, StreamHandler.php

### ISSUE THREAD

**Issue by frostytsnowman** [eckmarcommunity/eckmar#50] opened 2022-09-26 21:44 UTC
having an issue with set up, probably something wrong with installation but does anyone know what?

<img width="1440" alt="Screen Shot 2022-09-26 at 5 42 41 PM" src="https://user-images.githubusercontent.com/113392326/192386183-af2c658d-9636-41bf-ac2d-4046b733f302.png">

**Comment by dclipca** [comment] 2022-09-29 10:09
> having an issue with set up, probably something wrong with installation but does anyone know what?
> 
> <img alt="Screen Shot 2022-09-26 at 5 42 41 PM" width="1440" src="https://user-images.githubusercontent.com/113392326/192386183-af2c658d-9636-41bf-ac2d-4046b733f302.png">
```
I would check the permissions to the storage and make sure all other permissions were setup correctly. See below.
https://github.com/eckmarcommunity/eckmar/blob/master/INSTALLATION.md#permissions
```
More on a similar error on https://github.com/eckmarcommunity/eckmar/issues/41.

**Comment by Gralien** [comment] 2022-11-02 15:51
is it a directory or a file? does it exist? permissions and groups?

**Comment by justrawdata** [comment] 2022-12-13 22:27
I am also stuck at this error. It happened when creating an account. I feel it's related to permissions too, but unsure of a fix at the moment. I had a permission error during setup at this stage:

php artisan db:seed


I will recreate it and share the results in a moment!

**Comment by justrawdata** [comment] 2022-12-13 23:46
![image](https://user-images.githubusercontent.com/77526780/207469357-a64a09c7-3dfa-442c-839b-6ca958e9a422.png)

This is the cause of the error. I've tried numerous times to change permissions and get past this, but I'm having no luck. Any suggestions? 

This error results in the page shown in this issue and issue #51 .

**Comment by dclipca** [comment] 2023-04-15 12:33
Happy it worked out, @justrawdata. I am closing this issue. Please open if it happens again.

**Closed by dclipca** 2023-04-15 12:33 UTC
